### ISSUE TITLE
Watching fails to process files

### ISSUE THREAD

**Issue by druska** [jlmakes/karma-rollup-preprocessor#55]
This may be a config issue but I can't get auto watch working with my setup. Tests run fine the first time then rollup throws an exception when files change.

The command I running is: `npx karma start --auto-watch`

The error I get is:

```
02 08 2019 14:24:01.520:ERROR [preprocessor.rollup]: Failed to process ./src/ui/__tests__/mytest.spec.js

Error: Could not resolve entry module (src/ui/__tests__/mytest.spec.js).
    at error (/usr/src/app/components/node_modules/rollup/dist/rollup.js:9421:30)
    at pluginDriver.hookFirst.then.resolveIdResult (/usr/src/app/components/node_modules/rollup/dist/rollup.js:16241:20)

02 08 2019 14:24:01.521:ERROR [karma-server]: UnhandledRejection

```

<details><summary>karma config</summary>
<p>

```js
const commonjs = require("rollup-plugin-commonjs")
const resolve = require("rollup-plugin-node-resolve")
const tsPlugin = require("rollup-plugin-typescript2")
const ttypescript = require("ttypescript")
const istanbul = require("rollup-plugin-istanbul")
const path = require("path")

module.exports = function(config) {
  config.set({
    frameworks: ["mocha"],

    reporters: ["mocha"],

    files: [
      { pattern: "src/test/globals.ts", watched: false },
      { pattern: "src/**/*.spec.ts", watched: false },
      { pattern: "src/**/*.spec.tsx", watched: false },
    ],

    preprocessors: {
      "src/test/globals.ts": ["rollup"],
      "src/**/*.spec.ts": ["rollup"],
      "src/**/*.spec.tsx": ["rollup"],
    },

    rollupPreprocessor: {
      /**
       * This is just a normal Rollup config object,
       * except that `input` is handled for you.
       */
      output: {
        format: "iife",
        name: "agentmessenger",
        sourcemap: "inline",
      },
      plugins: [
        resolve(),
        commonjs({
          namedExports: { chai: ["assert"] },
          sourceMap: false,
        }),
        tsPlugin({
          typescript: ttypescript,
        }),
        istanbul({
          exclude: ["src/**/*.spec.ts", "src/**/*.spec.tsx"],
        }),
      ],
      onwarn: warning => {
        if (
          warning.code === "CIRCULAR_DEPENDENCY" &&
          warning.importer.indexOf("node_modules/chai/lib/chai.js") === 0
        ) {
          // Chai contains circular references, but they are not fatal and can be ignored.
          return
        }

        console.warn(`(!) ${warning.message}`)
      },
    },

    coverageIstanbulReporter: {
      reports: ["lcovonly", "text-summary"],
      dir: path.join(__dirname, "coverage"),
      combineBrowserReports: true,
    },

    junitReporter: {
      outputDir: "reports", // results will be saved as $outputDir/$browserName.xml
      outputFile: "results.xml", // if included, results will be saved as $outputDir/$browserName/$outputFile
      useBrowserName: false, // add browser name to report and classes names
    },

    client: {
      mocha: {
        reporter: "html",
        require: [],
      },
    },

    browsers: ["custom_chromium"],

    customLaunchers: {
      custom_chromium: {
        base: "ChromiumHeadless",
        flags: ["--disable-dev-shm-usage", "--no-sandbox", "--disable-web-security"],
      },
    },
  })
}
```

</p>
</details>

package.json:

<details><summary>package.json dependencies</summary>
<p>

```json
{
  "@types/chai": "^4.1.7",
  "@types/mocha": "^5.2.7",
  "chai": "^4.2.0",
  "karma": "^4.2.0",
  "karma-chrome-launcher": "^3.0.0",
  "karma-coverage-istanbul-reporter": "^2.1.0",
  "karma-junit-reporter": "^1.2.0",
  "karma-mocha": "^1.3.0",
  "karma-mocha-reporter": "^2.2.5",
  "karma-rollup-preprocessor": "^7.0.2",
  "mocha": "^6.2.0",
  "node-sass": "^4.12.0",
  "puppeteer": "^1.19.0",
  "rollup": "^1.19.3",
  "rollup-plugin-commonjs": "^10.0.2",
  "rollup-plugin-istanbul": "^2.0.1",
  "rollup-plugin-multi-entry": "^2.1.0",
  "rollup-plugin-node-resolve": "^5.2.0",
  "rollup-plugin-typescript2": "^0.22.1",
  "ttypescript": "^1.5.7",
  "typescript": "^3.5.3"
}
```

</p>
</details>

**Comment by jlmakes** [comment]
Does this happen with both `karma-rollup-preprocessor@7.0.0` and `7.0.2` ??

**Comment by druska** [comment]
This occurs on 7.0.2 (I updated my post with versions).

`karma-rollup-preprocessor@7.0.0` doesn't run once - I get the following error:
```
bash-5.0# npx karma start --auto-watch
06 08 2019 13:35:29.706:WARN [filelist]: Pattern "/usr/src/app/components/src/**/*.spec.tsx" does not match any file.
06 08 2019 13:35:35.197:INFO [preprocessor.rollup]: Generating bundle for ./src/test/globals.ts
06 08 2019 13:35:49.928:INFO [preprocessor.rollup]: Generating bundle for ./src/ds/__tests__/mytest.spec.ts
06 08 2019 13:35:51.993:WARN [karma]: No captured browser, open http://localhost:9876/
06 08 2019 13:35:52.005:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/
06 08 2019 13:35:52.005:INFO [launcher]: Launching browsers custom_chromium with concurrency unlimited
06 08 2019 13:35:52.029:INFO [launcher]: Starting browser ChromiumHeadless
06 08 2019 13:35:52.558:INFO [HeadlessChrome 73.0.3683 (Linux 0.0.0)]: Connected on socket 7--WvQD0_AZZKnF_AAAA with id 72939777

START:
06 08 2019 13:35:52.577:WARN [middleware:karma]: Invalid file type (ts), defaulting to js.
06 08 2019 13:35:52.577:WARN [middleware:karma]: Invalid file type (ts), defaulting to js.

Finished in 0.003 secs / 0 secs @ 13:35:52 GMT+0000 (Coordinated Universal Time)

SUMMARY:
✔ 0 tests completed

```

**Comment by jlmakes** [comment]
Hmmm, good to see the TypeScript support introduced in `7.0.2` was indeed an enhancement. I'm still looking into that error message, but it seems to have come a few times for other developers using Rollup.

**Comment by druska** [comment]
It looks like this might be an issue with karma. `karma-rollup-preprocessor` emits the correct file path to `karma` via `changeFile`, but karma is looking for `path.path` instead of `path.originalPath`. I'll continue to investigate

**Comment by jlmakes** [comment]
I'm not really sure what the difference between `path` and `originalPath` is. I vaguely remember finding they contained the same string, but I'm mostly flying by the seat of my pants.

I'll take a closer look.

**Comment by druska** [comment]
For my setup, path was a `.js` file (which didn't exist) and originalPath was a correct `.ts` file
