### ISSUE TITLE
[support] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bennypowers** [jlmakes/karma-rollup-preprocessor#67]
Hello and thank you for maintaining this project.

I've set up the following config file, based on the open-wc config for karma-esm and my project's rollup config.

**NOTE** that I'm building to esm here.

<details>
  <summary>karma.conf.js</summary>

```js
const dotenv = require('dotenv');
const path = require('path');

const alias = require('@rollup/plugin-alias');
const commonjs = require('@rollup/plugin-commonjs');
const json = require('@rollup/plugin-json');
const replace = require('@rollup/plugin-replace');
const resolve = require('@rollup/plugin-node-resolve');
const babel = require('rollup-plugin-babel');
const graphql = require('@kocal/rollup-plugin-graphql');
const indexHTML = require('rollup-plugin-index-html');
const litcss = require('rollup-plugin-lit-css');

dotenv.config();

const PROCESS_WATCHING =
  process.argv.some(arg => arg.match(/-c?w/)) || process.argv.includes('--watch');

const production = !PROCESS_WATCHING && process.env.NODE_ENV === 'production';

const coverage = process.argv.find(arg => arg.includes('--coverage'));

const replaceConfig = {
   ...redacted
};

module.exports = config => {
  const customResolver = resolve({
    extensions: ['.js', '.json', '.html', '.graphql', '.css'],
    dedupe: id => id.includes('lit'),
  });

  config.set({
    browsers: ['ChromeHeadlessNoSandbox'],

    files: [
      'src/**/*.test.js',
    ],

    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox', '--disable-setuid-sandbox'],
      },
    },

    plugins: ['karma-*'],

    frameworks: ['mocha', 'source-map-support'],

    preprocessors: {
      'src/**/*.spec.js': ['rollup'],
    },

    rollupPreprocessor: {
      options: {
        output: { format: 'esm', dir: 'build', sourcemap: true },
        plugins: [
          replace(replaceConfig),
          babel(),
          indexHTML(),
          alias({ entries: [{
            find: /^#(.*)\/(.*)\b/,
            replacement: path.resolve(__dirname, 'src/$1/$2'),
          }, {
            find: /^#(.*)\b/,
            replacement: path.resolve(__dirname, 'src/$1'),
          }], customResolver }),
          customResolver,
          commonjs({ sourceMap: false }),
          graphql(),
          json(),
          litcss({ uglify: false }),
        ],
        // Don't warn about `this` - typescript produces these.
        onwarn(warning, warn) {
          if (warning.code === 'THIS_IS_UNDEFINED') return;
          warn(warning);
        },

      },
    },

    reporters: coverage ? ['mocha', 'coverage-istanbul'] : ['mocha'],

    mochaReporter: {
      showDiff: true,
    },

    restartOnFileChange: true,

    client: {
      mocha: {
        reporter: 'html',
      },
    },

    colors: true,

    // possible values: LOG_DISABLE || LOG_ERROR || LOG_WARN || LOG_INFO || LOG_DEBUG
    logLevel: config.LOG_INFO,

    // ## code coverage config
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly', 'text-summary'],
      dir: 'coverage',
      combineBrowserReports: true,
      skipFilesWithNoCoverage: false,
      thresholds: {
        global: {
          statements: 80,
          branches: 80,
          functions: 80,
          lines: 80,
        },
      },
    },

    autoWatch: false,
    singleRun: true,
    concurrency: Infinity,
  });
  return config;
};
```
</details>
<details>
<summary>comparison.test.js</summary>

```js
import { expect } from '@open-wc/testing';
import { comparison } from './comparison';

function mockAnalysis(size) {
  return {
    __typename: 'Analysis',
    size
  };
}

describe('comparison', function() {
  it('formats a figure as percentage of a New York', function() {
    expect(comparison(mockAnalysis(124669095), null, null, null)).to.equal('5% the size of New York');
  });
});
```
</details>

Result:
```
> neuerenergy-pwa@0.1.0 test /Users/bennyp/Documents/neuerenergy-pwa
> npx karma start --coverage


START:
26 03 2020 21:40:40.547:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
26 03 2020 21:40:40.549:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
26 03 2020 21:40:40.553:INFO [launcher]: Starting browser ChromeHeadless
26 03 2020 21:40:41.161:INFO [HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)]: Connected on socket I4tB12fljCoGi47YAAAA with id 1833668
HeadlessChrome 80.0.3987 (Mac OS X 10.14.6) ERROR
  Uncaught SyntaxError: Cannot use import statement outside a module
  at src/components/analysis/resolvers/Analysis/comparison.test.js:1:1

  SyntaxError: Cannot use import statement outside a module
HeadlessChrome 80.0.3987 (Mac OS X 10.14.6) ERROR
  Uncaught SyntaxError: Cannot use import statement outside a module
  at src/components/analysis/resolvers/Analysis/comparison.test.js:1:1

  SyntaxError: Cannot use import statement outside a module

Finished in 0.115 secs / 0 secs @ 21:40:41 GMT+0200 (Israel Standard Time)

SUMMARY:
✔ 0 tests completed

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

I'd appreciate any guidance you're able to give

Thanks!

**Comment by bennypowers** [comment]
Ugh so much fail. I set config to preprocess `.spec.js` instead of `.test.js`

I'll see myself out
